const REASON={en:{
  "auth.police":"They claim to be police, CBI, or customs. Real agencies never arrest anyone by phone or video call.",
  "auth.judge":"They mention courts or warrants. Courts do not work over calls or WhatsApp.",
  "auth.courier":"They claim to be a courier company about a suspicious parcel. Couriers never call about drugs in parcels.",
  "auth.bank":"They claim urgent bank or KYC action. Banks never ask you to act via a random number or link.",
  "auth.utility":"They threaten your electricity or SIM. Real notices carry your consumer ID, not a personal number.",
  "auth.govt":"They claim a PAN or Aadhaar problem. The government does not threaten instant deactivation by SMS.",
  "auth.celebrity":"A celebrity is shown endorsing big returns. These videos are usually deepfakes.",
  "auth.family_clone":"They claim to be family from a new or unknown number. Call the person's saved number first.",
  "auth.employer":"An unknown recruiter offering easy money is a common trap opening.",
  "fear.arrest_threat":"They threaten arrest to frighten you into paying.",
  "fear.digital_arrest":"They used the words digital arrest. No such thing exists in Indian law.",
  "fear.isolation":"They tell you to stay on the line and not tell anyone. Scams isolate you on purpose.",
  "fear.deadline":"They rush you with a deadline so you cannot stop and think.",
  "fear.account_block":"They threaten to block your account or connection to create panic.",
  "fear.legal_case":"They claim a case, FIR, or drugs to scare you.",
  "fear.emergency_urgency":"An urgent emergency plus a money request is a classic pressure tactic.",
  "fear.shame_threat":"They threaten to shame you with photos. That is extortion. Report it, never pay.",
  "fear.sunk_cost":"They say your money is stuck unless you pay more. That is how task scams trap people deeper.",
  "pay.deposit_refundable":"They ask for a refundable deposit for verification. No real agency works this way.",
  "pay.tax_fee_unlock":"They want a fee or tax to release your own money. That is always a scam.",
  "pay.qr_to_receive":"They ask you to scan a QR or enter a PIN to receive money. Receiving money never needs a PIN or QR.",
  "pay.collect_request":"An unexpected collect request takes money from you, it does not give it.",
  "pay.refund_return_ask":"They claim money was sent by mistake and want it back. Check your real bank balance first.",
  "pay.prepaid_task_deposit":"They want a deposit to unlock tasks or earnings. Real work never asks you to pay first.",
  "pay.fee_advance":"They want an advance fee for a loan, job, or prize. Legitimate offers never do.",
  "pay.gift_card_crypto":"They demand gift cards or crypto. That is a strong scam signal.",
  "pay.screen_share":"They ask you to install AnyDesk or share your screen. That lets them empty your account.",
  "pay.upi_individual":"Payment is demanded on a personal UPI handle for an official matter.",
  "pay.demand":"They are directly demanding a money transfer.",
  "pay.small_payout_lure":"Small easy payouts are the bait before they ask for deposits.",
  "chan.intl_number":"The contact comes from an unusual international number claiming to be an Indian authority.",
  "chan.video_call_official":"Official proceedings over Skype or WhatsApp video are fake. Agencies do not work this way.",
  "chan.ivr_press1":"A robocall asking you to press 1 is a common scam opening.",
  "chan.app_switch":"They push you to move to Skype, Zoom, or a special app. Do not install it.",
  "chan.apk_download":"They want you to install an app from outside the official store. Do not.",
  "chan.shortlink":"There is a shortened or odd link. Do not click it.",
  "chan.new_number_known_photo":"A familiar person on a brand new number is a red flag. Call their real number.",
  "chan.group_invite":"You are pushed into an earnings or tips group full of fake members.",
  "chan.personal_number_official":"Official business is being done from a personal 10-digit mobile number.",
  "content.otp_request":"They ask for your OTP, PIN, or CVV. Never share these with anyone.",
  "content.too_good_returns":"Guaranteed or daily returns are not real. This is an investment trap.",
  "content.lottery_prize":"You cannot win a lottery you never entered. KBC-style prize messages are scams.",
  "content.deepfake_media":"The investment video is very likely an AI deepfake.",
  "content.doctored_doc":"The warrant or notice with your details is fabricated.",
  "content.fake_screenshot":"A payment screenshot is not proof. Check your own bank app.",
  "content.morphed_media_threat":"Threatening with morphed photos is blackmail. Save evidence and report it.",
  "content.typos_leetspeak":"Odd spellings and symbols are used to dodge spam filters. Real institutions do not write this way.",
  "content.generic_greeting":"A generic greeting with no name or ID suggests a mass scam message."
}};

REASON.hi={
  "auth.police":"ये पुलिस, सीबीआई या कस्टम होने का दावा करते हैं। असली एजेंसी फ़ोन या वीडियो कॉल पर गिरफ़्तार नहीं करती।",
  "auth.judge":"ये कोर्ट या वारंट की बात करते हैं। अदालतें कॉल या WhatsApp पर काम नहीं करतीं।",
  "auth.courier":"ये कूरियर कंपनी होने का दावा करते हैं। कूरियर पार्सल में ड्रग्स के लिए कॉल नहीं करते।",
  "auth.bank":"ये बैंक या KYC की जल्दबाज़ी दिखाते हैं। बैंक कभी अनजान नंबर या लिंक से काम नहीं कराता।",
  "auth.utility":"ये बिजली या सिम बंद करने की धमकी देते हैं। असली सूचना में उपभोक्ता आईडी होती है।",
  "auth.govt":"ये पैन या आधार की समस्या बताते हैं। सरकार SMS पर तुरंत बंद करने की धमकी नहीं देती।",
  "auth.celebrity":"सेलिब्रिटी को मुनाफ़े का प्रचार करते दिखाया गया है। ऐसे वीडियो अक्सर डीपफेक होते हैं।",
  "auth.family_clone":"ये नए नंबर से परिवार का होने का दावा करते हैं। पहले सेव किए नंबर पर कॉल करें।",
  "auth.employer":"अनजान भर्तीकर्ता का आसान कमाई का ऑफ़र जाल की शुरुआत है।",
  "fear.arrest_threat":"डराकर पैसे निकलवाने के लिए गिरफ़्तारी की धमकी।",
  "fear.digital_arrest":"इन्होंने डिजिटल अरेस्ट कहा। भारतीय क़ानून में ऐसा कुछ नहीं होता।",
  "fear.isolation":"ये कहते हैं लाइन पर रहो, किसी को मत बताओ। स्कैम जानबूझकर अकेला करता है।",
  "fear.deadline":"सोचने का समय न मिले इसलिए जल्दबाज़ी कराते हैं।",
  "fear.account_block":"घबराहट के लिए खाता या कनेक्शन बंद करने की धमकी।",
  "fear.legal_case":"डराने के लिए केस, FIR या ड्रग्स का दावा।",
  "fear.emergency_urgency":"आपातकाल और पैसों की माँग पुरानी दबाव की चाल है।",
  "fear.shame_threat":"फ़ोटो से बदनामी की धमकी जबरन वसूली है। रिपोर्ट करें, पैसे न दें।",
  "fear.sunk_cost":"कहते हैं पैसा फँसा है, और डालो। टास्क स्कैम ऐसे ही गहरा फँसाता है।",
  "pay.deposit_refundable":"वेरिफ़िकेशन के नाम पर रिफ़ंडेबल जमा। कोई असली एजेंसी ऐसा नहीं करती।",
  "pay.tax_fee_unlock":"अपने ही पैसे निकालने के लिए टैक्स या फ़ीस। यह हमेशा स्कैम है।",
  "pay.qr_to_receive":"पैसे पाने के लिए QR स्कैन या PIN। पैसे पाने में PIN कभी नहीं लगता।",
  "pay.collect_request":"अनचाही कलेक्ट रिक्वेस्ट पैसे लेती है, देती नहीं।",
  "pay.refund_return_ask":"कहते हैं ग़लती से पैसे गए, लौटाओ। पहले अपना असली बैलेंस देखें।",
  "pay.prepaid_task_deposit":"कमाई खोलने के लिए जमा। असली काम पहले पैसे नहीं माँगता।",
  "pay.fee_advance":"लोन, नौकरी या इनाम के लिए अग्रिम फ़ीस स्कैम है।",
  "pay.gift_card_crypto":"गिफ़्ट कार्ड या क्रिप्टो की माँग बड़ा ख़तरे का संकेत है।",
  "pay.screen_share":"AnyDesk या स्क्रीन शेयर से वे खाता खाली कर सकते हैं।",
  "pay.upi_individual":"सरकारी काम के लिए निजी UPI पर पैसे माँगे जा रहे हैं।",
  "pay.demand":"सीधे पैसे ट्रांसफ़र करने की माँग है।",
  "pay.small_payout_lure":"छोटी कमाई चारा है, आगे जमा माँगेंगे।",
  "chan.intl_number":"भारतीय एजेंसी के नाम पर विदेशी नंबर से संपर्क।",
  "chan.video_call_official":"स्काइप या वीडियो कॉल पर सरकारी कार्रवाई नकली होती है।",
  "chan.ivr_press1":"1 दबाइए वाली रोबो कॉल स्कैम की आम शुरुआत है।",
  "chan.app_switch":"स्काइप, ज़ूम या ख़ास ऐप पर ले जाना चाहते हैं। इंस्टॉल न करें।",
  "chan.apk_download":"स्टोर के बाहर से ऐप इंस्टॉल कराना चाहते हैं। न करें।",
  "chan.shortlink":"संदिग्ध छोटा लिंक है। क्लिक न करें।",
  "chan.new_number_known_photo":"जान-पहचान वाले का नया नंबर संदिग्ध है। असली नंबर पर कॉल करें।",
  "chan.group_invite":"नकली सदस्यों वाले कमाई ग्रुप में डाला जा रहा है।",
  "chan.personal_number_official":"सरकारी काम निजी मोबाइल नंबर से हो रहा है।",
  "content.otp_request":"OTP, PIN या CVV माँग रहे हैं। किसी को न बताएं।",
  "content.too_good_returns":"गारंटीड या रोज़ का मुनाफ़ा असली नहीं होता।",
  "content.lottery_prize":"जो लॉटरी आपने खेली ही नहीं, वह जीत नहीं सकते। KBC इनाम संदेश स्कैम हैं।",
  "content.deepfake_media":"निवेश वीडियो शायद AI डीपफेक है।",
  "content.doctored_doc":"आपकी जानकारी वाला वारंट या नोटिस नकली है।",
  "content.fake_screenshot":"पेमेंट स्क्रीनशॉट सबूत नहीं। अपना बैंक ऐप देखें।",
  "content.morphed_media_threat":"मॉर्फ़्ड फ़ोटो की धमकी ब्लैकमेल है। सबूत रखें, रिपोर्ट करें।",
  "content.typos_leetspeak":"फ़िल्टर से बचने के लिए अजीब स्पेलिंग। असली संस्थाएँ ऐसे नहीं लिखतीं।",
  "content.generic_greeting":"बिना नाम/आईडी का सामान्य अभिवादन मास स्कैम का संकेत है।"
};

const NEXT={en:{
  danger:"Do not pay, click, or share anything. If you are on a call, hang up now. Call 1930 and tell a family member.",
  care:"Slow down and verify independently. Open the official app yourself, or call the person or company on a number you already have. Do not use the number or link they gave you.",
  safe:"Nothing strongly suspicious found. Still, never share OTP or PIN, and verify anything about money before acting."
},hi:{
  danger:"कुछ भी न भेजें, क्लिक न करें, शेयर न करें। कॉल पर हैं तो अभी काटें। 1930 पर कॉल करें और परिवार को बताएं।",
  care:"रुकें और खुद जाँचें। आधिकारिक ऐप खुद खोलें या अपने पास मौजूद नंबर पर कॉल करें। इनका दिया नंबर या लिंक इस्तेमाल न करें।",
  safe:"कोई बड़ा ख़तरा नहीं दिखा। फिर भी OTP या PIN कभी शेयर न करें, पैसों की बात पहले जाँचें।"
}};

const TIER_LABEL={en:{danger:"DANGER",care:"BE CAREFUL",safe:"LOOKS SAFE"},hi:{danger:"ख़तरा",care:"सावधान रहें",safe:"सुरक्षित लगता है"}};

const EVAL_NAME={en:{E1:"Authority",E2:"Fear tactics",E3:"Payment",E4:"Channel",E5:"Content"},hi:{E1:"प्राधिकरण",E2:"डर की चालें",E3:"भुगतान",E4:"माध्यम",E5:"सामग्री"}};

export { REASON, NEXT, TIER_LABEL, EVAL_NAME };
